molecule: use the new charts repository
Since October, 26th, the sable repository has a new location.
See: https://helm.sh/blog/new-location-stable-incubator-charts/

Without this change, the test-suite fails because of the following
error:

```
$ `helm repo add test_helm_repo https://kubernetes-charts.storage.googleapis.com`
Error: repo "https://kubernetes-charts.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/stable" instead
```